#
# Default config
#

cli:
  app:
    serve:
      config: '~/.wire/remote.yml'
      loginApp: 'dxos:application/keyhole'
      keyPhrase: 'GoxWtucubK'
  console:
    package: '@dxos/console-server'
    channel: 'alpha'
    bin: 'dxos-console'
  mdns:
    package: '@dxos/mdns'
    channel: 'beta'
    bin: 'dxos-mdns'
  signal:
    package: '@dxos/signal'
    channel: 'alpha'
    bin: 'dxos-signal'
  npmClient: 'yarn' # npm|yarn
  channel: 'alpha'

# DXOS services.
services:
  wns:
    server: 'http://127.0.0.1:9473/api'
    webui: 'http://127.0.0.1:9473/console'
    userKey:
    bondId:
    chainId: moon
    gas: '200000'
    fees: '200000uwire'
  dxns:
    server: 'ws://127.0.0.1:9944'
    accountUri:
  ipfs:
    server: 'http://127.0.0.1:5001'
    gateway: 'http://127.0.0.1:8888/ipfs/'
  signal:
    server: 'ws://127.0.0.1:4000'
    api: 'http://127.0.0.1:4000'
  ice:
    - urls: 'stun:apollo1.kube.moon.dxos.network:3478'
    - urls: 'turn:apollo1.kube.moon.dxos.network:3478'
      username: 'dxos'
      credential: 'dxos'
    - urls: 'stun:apollo2.kube.moon.dxos.network:3478'
    - urls: 'turn:apollo2.kube.moon.dxos.network:3478'
      username: 'dxos'
      credential: 'dxos'
  faucet:
    server: 'https://node1.dxos.network/faucet/api'
  kube:
    publicUrl: '/console'
  app:
    prefix: '/app'
    server: 'http://127.0.0.1:5999'
    
system:
  certEndpoint: ''