#
# Default config
#

cli:
  app:
    serve:
      config: '~/.dx/remote.yml'
  console:
    package: '@dxos/console-server'
    channel: 'beta'
    bin: 'dxos-console'
  signal:
    package: '@dxos/signal'
    channel: 'beta'
    bin: 'dxos-signal'
  mdns:
    package: '@dxos/mdns'
    channel: 'beta'
    bin: 'dxos-mdns'
  npmClient: 'npm' # npm|yarn
  channel: 'beta'

# DXOS services.
services:
  registry:
    server: 'http://127.0.0.1:9473/api'
    userKey: 'b1e4e95dd3e3294f15869b56697b5e3bdcaa24d9d0af1be9ee57d5a59457843a'
    bondId: '8e340dd7cf6fc91c27eeefce9cca1406c262e93fd6f3a4f3b1e99b01161fcef3'
    chainId: 'localnet'
    gas: '200000'
    fees: '200000udxt'
  ipfs:
    server: '/ip4/127.0.0.1/tcp/5001'
    gateway: 'http://127.0.0.1:8888/ipfs/'
  signal:
    server: 'ws://127.0.0.1:4000'
  ice:
    - urls: 'stun:night.2e1a47.xyz:3478'
    - urls: 'turn:night.2e1a47.xyz:3478'
      username: 'dxos'
      credential: 'dxos'
  faucet:
    server: ''
system:
  certEndpoint: ''
