build: yarn build
name: TestApp
package:
  /: QmRAkSH88J8tG4Woy3jcaBVAmQzoDtdAaeqGo7H8oRtajr
description: Mock application
repositoryVersion: v2.12.0-10-gcdc54c95e78c68816438999c1e5858a5afc9967f-dirty
tag:
  - latest
  - beta
version: 2.0.1
