build: yarn build
name: TestApp
package:
  /: QmRAkSH88J8tG4Woy3jcaBVAmQzoDtdAaeqGo7H8oRtajr
description: Mock application
repositoryVersion: v2.11.4-20-g782fa78ea30f12d755ad4d30367cd1ab620a9166-dirty
version: 2.0.1
tag:
  - latest
  - beta
