build: yarn build
name: TestApp
package:
  /: QmRAkSH88J8tG4Woy3jcaBVAmQzoDtdAaeqGo7H8oRtajr
description: Mock application
repositoryVersion: v2.13.11-0-g4a90b45abdb703e679f50ff1d628279493245147-dirty
tag:
  - latest
  - beta
version: 2.0.1
