version: '3'
services:
  kube:
    image: "ghcr.io/dxos/kube"
    container_name: kube
    hostname: kube.local
    ports:
      - 443: '443'
      - 5001: '5001'
      - 8888: '8888'
      - 9473: '9473'
    command: /opt/kube/scripts/run.sh
