- package: '@dxos/cli-signal'
  service: 'signal'
  args: '--asBootstrap'
- package: '@dxos/cli-ipfs'
  service: 'ipfs'
- package: '@dxos/cli-app'
  service: 'app-server'
- package: '@dxos/cli-dxns'
  service: 'dxns'
- package: '@dxos/cli-bot'
  service: 'bot-factory'
