version: '3'
services:
  dxns:
    image: "ghcr.io/dxos/substrate-node"
    container_name: dxns
    ports:
      - 9944: '9944'
    volumes:
      - storage:/dxns/node
    command: node-template --dev --base-path /dxns/node --rpc-cors all -lsync=warn -lconsole-debug --ws-external --rpc-external
