#!/bin/bash

set -euo pipefail

EXTENSION_FILE="./extension.yml"
KNOWN_EXTENSIONS_FILE="./known-extensions.yml"

EXTENSIONS="["

for extensiondir in `find ../ -name 'cli-*' -type d | grep -v node_modules | sort`; do
  pushd $extensiondir

  if [ -f "$EXTENSION_FILE" ]; then
    if [ "$EXTENSIONS" != "[" ]; then
      EXTENSIONS+=","
    fi
    EXTENSIONS+=` yarn --silent yaml2json "$EXTENSION_FILE"`
  fi

  popd
done

EXTENSIONS+="]"

echo "# This is an autogenerated file. Do not edit this file directly." > $KNOWN_EXTENSIONS_FILE
echo $EXTENSIONS | jq '[.[] | {moduleName:("@" + .name), describe: .description, command: .command, initRequired: (.initRequired // false), destroyRequired: (.destroyRequired // false)}]' | json2yaml >> $KNOWN_EXTENSIONS_FILE
