#!/bin/bash

set -euo pipefail

EXTENSION_FILE="extension.yml"
KNOWN_EXTENSIONS_FILE="./known-extensions.yml"

EXTENSIONS="["

MAIN_CWD="$(pwd)"

for extensiondir in `find ../ -name 'cli-*' -type d | grep -v node_modules | sort`; do
  pushd $extensiondir

  EXT_FILE_PATH=`find . -name $EXTENSION_FILE -not -path "./dist/*"`
  if [ -f "$EXT_FILE_PATH" ]; then
    # $MAIN_CWD/node_modules/.bin/js-yaml $EXTENSION_FILE
    if [ "$EXTENSIONS" != "[" ]; then
      EXTENSIONS+=","
    fi
    EXTENSIONS+=` $MAIN_CWD/node_modules/.bin/js-yaml $EXTENSION_FILE`
  fi

  popd
done

EXTENSIONS+="]"

echo "# This is an autogenerated file. Do not edit this file directly." > $KNOWN_EXTENSIONS_FILE
echo $EXTENSIONS | jq '[.[] | {moduleName:("@" + .name), describe: .description, command: .command, initRequired: (.initRequired // false), destroyRequired: (.destroyRequired // false)}]' | json2yaml >> $KNOWN_EXTENSIONS_FILE
