version: '3'
services:
  ipfs:
    image: "ghcr.io/dxos/ipfs"
    container_name: ipfs
    ports:
      - 5001: '5001'
      - 8888: '8888'
    volumes:
      - storage:/root/.ipfs
    command: "dx ipfs start --connect-interval 60"
