# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint, Build, and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - name: Lint, build, test
      run: |
        yarn
        yarn lint
        yarn build
        yarn test
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [16.x]
        lockfile: [lockfile, no-lockfile]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - name: Delete lockfile
      if: ${{ matrix.lockfile == 'no-lockfile' }}
      run: rm yarn.lock
    - name: Install dependencies
      run: yarn
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    - name: Build packages
      run: yarn build
    - name: E2E test
      run: yarn test:e2e
      working-directory: ./packages/e2e
     
