on:
  push:

name: Build, test, lint
jobs:
  check:
    runs-on: [self-hosted, dind-actions-runner]
    timeout-minutes: 25
    strategy:
      matrix:
        node-version: [16.1]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: false
      - name: Build, lint and test
        run: |
          \. "$NVM_DIR/nvm.sh" && nvm install ${{ matrix.node-version }} && nvm use ${{ matrix.node-version }}
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm install -g @microsoft/rush pnpm
          
          # Install dependencies
          node common/scripts/install-run-rush.js install
          
          # Build
          node common/scripts/install-run-rush.js build --verbose

          # Lint
          node common/scripts/install-run-rush.js lint --verbose

          # Test
          node common/scripts/install-run-rush.js test --verbose
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [16.x]
        lockfile: [lockfile, no-lockfile]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - name: Delete lockfile
      if: ${{ matrix.lockfile == 'no-lockfile' }}
      run: rm common/config/rush/pnpm-lock.yaml
    - name: Build, lint, test
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      run: |
          \. "$NVM_DIR/nvm.sh" && nvm install ${{ matrix.node-version }} && nvm use ${{ matrix.node-version }}
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm install -g @microsoft/rush pnpm
          
          # Install dependencies
          node common/scripts/install-run-rush.js install
          
          # Build
          node common/scripts/install-run-rush.js build --verbose

          # Lint
          node common/scripts/install-run-rush.js lint --verbose

          # Test
          node common/scripts/install-run-rush.js test --verbose
