name: Publish DXOS Service container to GitHub Registry

on:
  workflow_dispatch

jobs:
  # Push image to GitHub Packages.
  ghr_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
    - name: Build and Publish Docker Image
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        scripts/docker_build_release.sh dev
