on:
  push:
    branches:
      - main
name: main - release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: dxos/release-please-action@v0.0.100
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: '@dxos/sdk'
      # The logic below handles the npm publication:
      - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - name: Lerna Publish
        run: |
          git config --global user.email "npm@dxos.network"
          git config --global user.name "DXOS"
          yarn
          yarn build
          yarn lint
          yarn test
          git reset --hard
          yarn lerna version `echo "${{ steps.release.outputs.tag_name }}" | sed 's/^v//'`-alpha.0 --no-git-tag-version -y
          git commit -am "${{ steps.release.outputs.tag_name }}"-alpha.0
          git push
          git tag -f "${{ steps.release.outputs.tag_name }}"-alpha.0
          git push --tags -f
          git push --delete origin "${{ steps.release.outputs.tag_name }}"
          yarn lerna publish from-package --force-publish -y --dist-tag="alpha"
          yarn dx profile init --name $DX_PROFILE --template-url "$DX_PROFILE_URL"
          yarn dx machine delete --name alpha
          sleep 10
          yarn dx machine create --name alpha --cliver '@alpha' --register
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          DX_PROFILE: ci
          DX_PROFILE_URL: ${{secrets.dx_profile_url}}
          DX_REGISTRY_USER_KEY: ${{secrets.registry_user_key}}
          DX_REGISTRY_BOND_ID: ${{secrets.registry_bond_id}}
          DX_MACHINE_DO_TOKEN: ${{secrets.dx_machine_do_token}}
          DX_MACHINE_GITHUB_TOKEN: ${{secrets.dx_machine_github_token}}
          DX_MACHINE_DNS_DOMAIN: ${{secrets.dx_machine_dns_domain}}
        if: ${{ steps.release.outputs.release_created }}
